### PR TITLE
python event store interface

### PR DESCRIPTION
**Pull request by cbernet**
make sure the EventStore module can be found (pythonpath). 
re-added unittest as a test
removed python read.py that was a unittest and not an example script

### CODE REVIEW

**Comment by jlingema** [comment]
Hi Colin,
Maybe a better place for EventStore_test would be in tests/ or tests/python, what do you think? Also we could add the python test in the CMakeLists.
Cheers,
Joschka

**Comment by cbernet** [comment]
Hi Joschka, 

I’d really prefer to keep the tests in the same directory as the module they test, 
which is common practice in python. 
Otherwise I’m pretty sure I’ll stop writing tests because I’m too lazy to go and look for the test file in another directory. 

I can write a test suite module in tests/ or tests/python 
that would gather all python tests in the package.
Should we adopt tests/python then? 

That’s great if we can include them in the CMakeLists and make them part of the standard test suite! 

Cheers,

Colin

**Comment by jlingema** [comment]
Hi again,

OK, I don't really mind where the test is. I was only thinking how we are arranging things in FCCSW and thought that uniformity could be nice. 

Regarding a python test package: I'm not 100% sure how that would then interface with CTest. I'll make a PR to FCCSW later where I wrote a small doc on how to add python tests to the CMakeLists in FCCSW (but also more or less works generically with CTest). Maybe we can discuss once that's in place and see what you think?

Cheers,
Joschka

**Comment by cbernet** [comment]
ok!

**Comment by cbernet** [comment]
retest this please

**Comment by hegner** [comment]
Hi Colin. This request *failed* the automatic testing. Why did you merge?

**Comment by cbernet** [comment]
Hi, 

I merged because the test that fails is the python read. 
we discussed that yesterday, the test has to be adapted. 
So this is not an issue. 

On the other hand, this PR is actually making it possible for users to use the python read feature
as was the case before. 

Now I’m working on fixing the failing test. 
Could have split the PR but waste of time.

Colin

**Pull request merged**
