### PR TITLE
Update fcc-externals and add options

### PR DESCRIPTION
**Pull request by JavierCVilla**
BEGINRELEASENOTES
- Use LCG Release to set up the environment
- Update to LCG_94
- Add arguments to the script (compiler and fcc externals version)
  + This allows to use new compilers other than gcc62
- Do not rely on the PODIO env variable in the CMake configuration

ENDRELEASENOTES

### CODE REVIEW

**Comment by vvolkl** [comment]
Hi Javier, that's great, thanks. I have a somewhat general question: What is `init.sh` in this package supposed to do? if it is just building and testing podio, wouldn't it be more logical to setup the LCG_releases only, without the fcc-externals? Especially since podio may be used outside of FCC.

**Comment by vvolkl** [comment]
I think you can also submit these PR's already to the upstream (AIDAsoft) repo!

**Comment by gganis** [comment]
(I would not wait for Clement for this)

**Comment by JavierCVilla** [comment]
@vvolkl 

>  wouldn't it be more logical to setup the LCG_releases only, without the fcc-externals?

That's true, Podio can work only with the packages provided by the LCG releases so it makes more sense to only use those. I already changed it.

> Perhaps you can rebase on #75, the upstream changes in AIDASoft? I opened that a while ago, I think it needs some updates to the CI.

I can have a look but in a different PR, or maybe in #75.

**Comment by JavierCVilla** [comment]
> Perhaps you could add an help switch explaining the switches.

Done

**Comment by JavierCVilla** [comment]
@phsft-bot build

**Pull request merged**
